import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import TopHeader from "./componets/Header";
import SideNav from "./componets/SideNav";
import OpenSideNav from "./componets/OpenSideNav";

import StoreProvider from "./storeProvider";
import { makeStore } from "@/lib/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased bg-gray-800`}>
          <div className="relative pt-10 max-sm:pt-0 max-sm:pl-0">
            <TopHeader />
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
